.\" Copyright (c) 1983, 1990, 1992, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Распространение и использование в исходной и двоичной формах, с или без
.\" модификации, допускаются при соблюдении следующих условий:
.\" 
.\" 1. При повторном распространении исходного кода должно сохраняться вышеуказанное уведомление
.\"    об авторских правах, этот список условий и следующий отказ от ответственности.
.\" 2. При распространении в двоичной форме в документации и/или других материалах, прилагаемых к дистрибутиву,
.\"    должны быть воспроизведены вышеуказанное уведомление об авторских правах,
.\"    этот список условий и нижеследующий отказ от ответственности.
.\" 3. Ни название университета, ни имена его сотрудников
.\"    не могут быть использованы для рекламы или продвижения продуктов, созданных на основе данного программного обеспечения,
.\"    без специального предварительного письменного разрешения.
.\"
.\" ДАННОЕ ПРОГРАММНОЕ ОБЕСПЕЧЕНИЕ ПРЕДОСТАВЛЯЕТСЯ РЕГЕНТАМИ И АВТОРАМИ `КАК ЕСТЬ", И
.\" И МЫ ОТКАЗЫВАЕМСЯ ОТ ЛЮБЫХ ЯВНЫХ ИЛИ ПОДРАЗУМЕВАЕМЫХ ГАРАНТИЙ, ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ,
.\" ПОДРАЗУМЕВАЕМЫМИ ГАРАНТИЯМИ ТОВАРНОЙ ПРИГОДНОСТИ И ПРИГОДНОСТИ ДЛЯ ОПРЕДЕЛЕННОЙ ЦЕЛИ.
.\" НИ ПРИ КАКИХ ОБСТОЯТЕЛЬСТВАХ УПРАВЛЯЮЩИЕ ИЛИ СПОНСОРЫ НЕ НЕСУТ ОТВЕТСТВЕННОСТИ ЗА КАКИЕ-ЛИБО ПРЯМЫЕ,
.\" КОСВЕННЫЕ, СЛУЧАЙНЫЕ, ОСОБЫЕ, ПОКАЗАТЕЛЬНЫЕ ИЛИ КОСВЕННОПОСЛЕДОВАТЕЛЬНЫЕ УБЫТКИ (ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ,
.\" ПРИОБРЕТЕНИЕМ ЗАМЕНЯЮЩИХ ТОВАРОВ ИЛИ УСЛУГ; ПОТЕРЕЙ ВОЗМОЖНОСТИ ИСПОЛЬЗОВАНИЯ,
.\" ДАННЫХ ИЛИ ПРИБЫЛИ; ИЛИ ПЕРЕРЫВ В РАБОТЕ), НЕЗАВИСИМО ОТ ПРИЧИНЫ И НА ОСНОВАНИИ ЛЮБОЙ ТЕОРИИ ОТВЕТСТВЕННОСТИ,
.\" БУДЬ ТО В РАМКАХ КОНТРАКТА, СТРОГОЙ ОТВЕТСТВЕННОСТИ ИЛИ ПРАВОНАРУШЕНИЯ (ВКЛЮЧАЯ ХАЛАТНОСТЬ ИЛИ ИНОЕ НАРУШЕНИЕ),
.\" ВОЗНИКШЕГО КАКИМ-ЛИБО ОБРАЗОМ В РЕЗУЛЬТАТЕ ИСПОЛЬЗОВАНИЯ ДАННОГО ПРОГРАММНОГО ОБЕСПЕЧЕНИЯ,
.\" ДАЖЕ ЕСЛИ ВЫ БЫЛИ ПРЕДУПРЕЖДЕНЫ О ВОЗМОЖНОСТИ
.\" ТАКОГО УЩЕРБА.
.\"
.\"	@(#)netstat.1	8.8 (Berkeley) 4/18/94
.\"
.Dd Август 14, 2023
.Dt NETSTAT 1
.Os
.Sh НАИМЕНОВАНИЕ
.Nm netstat
.Nd показать состояния сети и статистики
.Sh КРАТКИЙ ОБЗОР
.Bk -words
.Bl -tag -width "netstat"
.It Nm
.Op Fl j Ar jail
.Op Fl -libxo
.Op Fl 46AaCLnPRSTWx
.Op Fl f Ar protocol_family | Fl p Ar protocol
.It Nm Fl i | I Ar interface
.Op Fl j Ar jail
.Op Fl -libxo
.Op Fl 46abdhnW
.Op Fl f Ar address_family
.Op Fl M Ar core
.Op Fl N Ar system
.It Nm Fl w Ar wait
.Op Fl j Ar jail
.Op Fl -libxo
.Op Fl I Ar interface
.Op Fl 46d
.Op Fl M Ar core
.Op Fl N Ar system
.Op Fl q Ar howmany
.It Nm Fl s
.Op Fl j Ar jail
.Op Fl -libxo
.Op Fl 46sz
.Op Fl f Ar protocol_family | Fl p Ar protocol
.Op Fl M Ar core
.Op Fl N Ar system
.It Nm Fl i | I Ar interface Fl s
.Op Fl j Ar jail
.Op Fl -libxo
.Op Fl 46s
.Op Fl f Ar protocol_family | Fl p Ar protocol
.Op Fl M Ar core
.Op Fl N Ar system
.It Nm Fl m
.Op Fl j Ar jail
.Op Fl -libxo
.Op Fl M Ar core
.Op Fl N Ar system
.It Nm Fl B
.Op Fl j Ar jail
.Op Fl -libxo
.Op Fl z
.Op Fl I Ar interface
.It Nm Fl r
.Op Fl j Ar jail
.Op Fl -libxo
.Op Fl 46nW
.Op Fl F Ar fibnum
.Op Fl f Ar address_family
.It Nm Fl rs
.Op Fl j Ar jail
.Op Fl -libxo
.Op Fl s
.Op Fl M Ar core
.Op Fl N Ar system
.It Nm Fl g
.Op Fl j Ar jail
.Op Fl -libxo
.Op Fl 46W
.Op Fl f Ar address_family
.It Nm Fl gs
.Op Fl j Ar jail
.Op Fl -libxo
.Op Fl 46s
.Op Fl f Ar address_family
.Op Fl M Ar core
.Op Fl N Ar system
.It Nm Fl Q
.Op Fl j Ar jail
.Op Fl -libxo
.El
.Ek
.Sh ОПИСАНИЕ

.Nm
команда показывает содержимое различных структур данных,
связанных с сетью.
Передаваемые аргументы определяют, какой из приведенных ниже выходных форматов
использует команда.
.Bl -tag -width indent
.It Xo
.Bk -words
.Nm
.Op Fl 46AaCLnRSTWx
.Op Fl f Ar protocol_family | Fl p Ar protocol
.Op Fl j Ar jail
.Ek
.Xc
Отобразить список активных сокетов
(блоки управления протоколом)
для каждого сетевого протокола.
.Pp
В режиме отображения по умолчанию для активных сокетов отображаются локальные
и удаленные адреса, размеры очереди отправки и получения (в байтах), протокол
и внутреннее состояние протокола.
Форматы адресов имеют следующий вид
.Dq host.port
или
.Dq network.port
если адрес сокета указывает сеть, но не указан конкретный адрес хоста.
Если он известен, адреса хоста и сети отображаются символически
в соответствии с базой данных
.Xr hosts 5
и
.Xr networks 5 ,
соответственно.
Если символьное имя для адреса неизвестно,
или если
.Fl n
если указан параметр, адрес выводится в цифровом виде в соответствии
с семейством адресов.
Для получения дополнительной информации об
IPv4 в Интернете
.Dq dot format ,
ссылается на
.Xr inet 3 .
Неуточненный,
или
.Dq wildcard ,
адреса и порты отображаются следующим образом
.Dq Li * .
.Bl -tag -width indent
.It Fl -libxo
Генерировать выходные данные с помощью
.Xr libxo 3
в различных форматах, удобочитаемых человеком и машиной.
Смотреть
.Xr xo_parse_args 3
для получения подробной информации об аргументах командной строки.
.It Fl 4
Показывать только IPv4.
Смотреть
.Sx GENERAL OPTIONS .
.It Fl 6
Показывать только IPv6.
Смотреть
.Sx GENERAL OPTIONS .
.It Fl A
Показывает адрес блока управления протоколом (PCB),
связанного с сокетом; используется для отладки.
.It Fl a
Показывает состояние всех сокетов;
обычно сокеты, используемые серверными процессами, не отображаются.
.It Fl c
Покажите используемый стек TCP для каждого сеанса.
.It Fl C
Покажите алгоритм контроля перегрузки и диагностическую информацию о TCP-сокетах.
.It Fl L
Показывает размер различных очередей прослушивания.
Первый подсчет показывает количество непринятых подключений,
второй подсчет показывает количество недопустимых незавершенных соединений,
и третье значение - это максимальное количество подключений в очереди.
.It Fl n
Не преобразуйте числовые адреса и номера портов в имена.
Смотреть
.Sx GENERAL OPTIONS .
.It Fl P
Отобразить идентификатор журнала для каждого сокета.
.It Fl R
Отобразить идентификатор потока и тип потока для каждого разъема.
идентификатор потока - это 32-разрядный аппаратный идентификатор для каждого потока.
тип потока определяет, какие поля протокола хэшируются для получения идентификатора.
Полный список доступен на сайте
.Pa sys/mbuf.h
под
.Dv M_HASHTYPE_* .
.It Fl S
Отображать сетевые адреса в виде цифр (как в
.Fl n )
но показывайте порты символически.
.It Fl T
Отобразить диагностическую информацию из блока управления TCP.
Поля включают количество пакетов, требующих повторной передачи,
принятых не по порядку и тех, которые указывают на окно нулевого размера.
.It Fl W
Избегайте усечения адресов, даже если это приводит к переполнению некоторых полей.
.It Fl x
Отображать статистику буфера сокета и таймера TCP для каждого
интернет-сокета.
.Pp

.Fl x
причины появления флага
.Nm
для вывода всей информации, записанной о данных,
хранящихся в буферах сокетов.
Эти поля являются:
.Bl -column ".Li R-HIWA"
.It Li R-HIWA Ta Получить наивысшую отметку буфера в байтах.
.It Li S-HIWA Ta Отправить буфер с наивысшей отметкой в байтах.
.It Li R-LOWA Ta Получить буфер с наименьшей отметкой в байтах.
.It Li S-LOWA Ta Отправить буфер с наименьшей отметкой в байтах.
.It Li R-BCNT Ta Получить количество байт в буфере.
.It Li S-BCNT Ta Отправить колличество байт в буфере.
.It Li R-BMAX Ta Максимальное количество байт, которые могут быть использованы в приемном буфере.
.It Li S-BMAX Ta Максимальное количество байт, которые могут быть использованы в буфере отправки.
.It Li rexmt Ta Время в секундах до срабатывания таймера повторной передачи или 0, если он не включен.
.It Li persist Ta Время, в секундах, до срабатывания повторной передачи сигнала, или 0, если он не включен.
.It Li keep Ta Время, в секундах, до срабатывания "Сохранить живым", или 0, если он не включен.
.It Li 2msl Ta Время срабатывания таймера TIME_WAIT в секундах 2*msl или 0, если он не включен.
.It Li delack Ta Время срабатывания таймера отложенного подтверждения в секундах или 0, если он не включен.
.It Li rcvtime Ta Время в секундах с момента получения последнего пакета.
.El
.It Fl f Ar protocol_family
Фильтровать по
.Ar protocol_family .
Смотреть
.Sx ОСНОВНЫЕ ПАРАМЕТРЫ .
.It Fl p Ar protocol
Фильтровать по
.Ar protocol .
Смотреть
.Sx GENERAL OPTIONS .
.It Fl j Ar jail
Запустить внутри jail.
Смотреть
.Sx GENERAL OPTIONS .
.El
.It Xo
.Bk -words
.Nm
.Fl i | I Ar interface
.Op Fl 46abdhnW
.Op Fl f Ar address_family
.Op Fl M Ar core
.Op Fl N Ar system
.Op Fl j Ar jail
.Ek
.Xc
Отображение состояния всех сетевых интерфейсов или одного из них
.Ar interface
которые были настроены автоматически
(интерфейсы, статически настроенные в системе, но отсутствующие
во время загрузки, не отображаются).
Звездочка
.Pq Dq Li *
после имени интерфейса указывается, что интерфейс является
.Dq down .
.Pp
Когда
.Nm
вызывается с помощью
.Fl i
.Pq all interfaces
или
.Fl I Ar interface ,
в нем представлена таблица совокупной
статистики о переданных пакетах, ошибках и коллизиях.
Сетевые адреса интерфейса
и максимальная скорость передачи.
.Pq Dq mtu
также отображаются.
Если оба
.Fl i
и
.Fl I
указаны,
.Fl I
переопределяет все экземпляры
.Fl i .
.Bl -tag -width indent
.It Fl 4
Показывать только IPv4.
Смотеть
.Sx GENERAL OPTIONS .
.It Fl 6
Показывать только IPv6.
Смотреть
.Sx GENERAL OPTIONS .
.It Fl a
Используемые в настоящее время адреса многоадресной рассылки отображаются
для каждого интерфейса Ethernet и для каждого адреса IP-интерфейса.
Адреса многоадресной рассылки отображаются в отдельных строках после
адреса интерфейса, с которым они связаны.
.It Fl b
Show the number of bytes in and out.
.It Fl d
Показывает количество входящих и исходящих байт.
.It Fl h
Распечатайте все счетчики в удобочитаемом виде.
.It Fl n
Не преобразуйте числовые адреса и номера портов в имена.
Смотреть
.Sx GENERAL OPTIONS .
.It Fl W
Избегайте усечения адресов, даже если это приводит к переполнению некоторых полей.
Смотреть
.Sx GENERAL OPTIONS .
Однако в большинстве случаев ширина полей определяется автоматически с помощью
.Fl i
вариант, и этот вариант имеет мало эффекта.
.It Fl f Ar protocol_family
Фильтровать по
.Ar protocol_family .
Смотреть
.Sx GENERAL OPTIONS .
.It Fl j Ar jail
Запустить внутри jail.
Сотреть
.Sx GENERAL OPTIONS .
.El
.It Xo
.Bk -words
.Nm
.Fl w Ar wait
.Op Fl I Ar interface
.Op Fl 46d
.Op Fl M Ar core
.Op Fl N Ar system
.Op Fl q Ar howmany
.Op Fl j Ar jail
.Ek
.Xc
С интервалом в
.Ar wait
секунд, отобразить информацию о пакетном трафике на всех
настроенных сетевых интерфейсах или на одном
.Ar interface .
.Pp
Когда
.Nm
вызывается с помощью
.Fl w
вариант и
.Ar wait
в качестве аргумента interval он отображает текущее количество статистических данных,
относящихся к сетевым интерфейсам.
Устаревшая версия этого параметра использовала числовой параметр
без опции и в настоящее время поддерживается для обеспечения обратной совместимости.
По умолчанию на этом дисплее отображается сводная информация для всех интерфейсов.
Информация для определенного интерфейса может отображаться с помощью
.Fl I Ar interface
опции
.Bl -tag -width indent
.It Fl I Ar interface
Показывать только информацию, касающуюся
.Ar interface
.It Fl 4
Показывать только IPv4.
Смотреть
.Sx GENERAL OPTIONS .
.It Fl 6
Показывать только IPv6.
Смотреть
.Sx GENERAL OPTIONS .
.It Fl d
Показывает количество отброшенных пакетов.
.It Fl M
Используйте альтернативное ядро.
Смотреть
.Sx GENERAL OPTIONS .
.It Fl N
Используйте альтернативный образ ядра.
Смотреть
.Sx GENERAL OPTIONS .
.It Fl q
Выйдите после
.Ar howmany
выходы.
.It Fl j Ar jail
Запустить внутри jail.
Смотреть
.Sx GENERAL OPTIONS .
.El
.It Xo
.Bk -words
.Nm
.Fl s
.Op Fl 46sz
.Op Fl f Ar protocol_family | Fl p Ar protocol
.Op Fl M Ar core
.Op Fl N Ar system
.Op Fl j Ar jail
.Ek
.Xc
Отображать общесистемную статистику по каждому сетевому протоколу.
.Bl -tag -width indent
.It Fl 4
Показывать только IPv4.
Смотреть
.Sx GENERAL OPTIONS .
.It Fl 6
Показывать только IPv6.
Смотреть
.Sx GENERAL OPTIONS .
.It Fl s
Или
.Fl s
повторяется, счетчики с нулевым значением отключаются.
.It Fl z
Сбросьте статистические счетчики после их отображения.
.It Fl f Ar protocol_family
Фильтровать по
.Ar protocol_family .
Смотреть
.Sx GENERAL OPTIONS .
.It Fl p Ar protocol
Фильтровать по
.Ar protocol .
Смотреть
.Sx GENERAL OPTIONS .
.It Fl M
Используйте альтернативное ядро.
Смотреть
.Sx GENERAL OPTIONS .
.It Fl N
Используйте альтернативный образ ядра
Смотреть
.Sx GENERAL OPTIONS .
.It Fl j Ar jail
Запустить внутри jail.
Смотреть
.Sx GENERAL OPTIONS .
.El
.It Xo
.Bk -words
.Nm
.Fl i | I Ar interface Fl s
.Op Fl 46s
.Op Fl f Ar protocol_family | Fl p Ar protocol
.Op Fl M Ar core
.Op Fl N Ar system
.Op Fl j Ar jail
.Ek
.Xc
Отображение статистики по каждому интерфейсу для каждого сетевого протокола.
если оба
.Fl i
и
.Fl I
указаны,
.Fl I
переопределяет все экземпляры
.Fl i .
.Bl -tag -width indent
.It Fl 4
Показывать только IPv4
Смотреть
.Sx GENERAL OPTIONS .
.It Fl 6
Показывать только IPv6
Смотреть
.Sx GENERAL OPTIONS .
.It Fl s
Или
.Fl s
повторяется, счетчики с нулевым значением отключаются.
.It Fl f Ar protocol_family
Фильтровать по
.Ar protocol_family .
Смотреть
.Sx GENERAL OPTIONS .
.It Fl p Ar protocol
Фильтровать по
.Ar protocol .
Смотреть
.Sx GENERAL OPTIONS .
.It Fl M
Используйте альтернативное ядро
Смотреть
.Sx GENERAL OPTIONS .
.It Fl N
Используйте альтернативный образ ядра
Смотреть
.Sx GENERAL OPTIONS .
.It Fl j Ar jail
Запустить внутри jail.
Смотреть
.Sx GENERAL OPTIONS .
.El
.It Xo
.Bk -words
.Nm
.Fl m
.Op Fl M Ar core
.Op Fl N Ar system
.Op Fl j Ar jail
.Ek
.Xc
Показывать статистику, записанную с помощью процедур управления памятью
.Pq Xr mbuf 9 .
Сеть управляет частным пулом буферов памяти.
.Bl -tag -width indent
.It Fl M
Используйте альтернативное ядро
Смотреть
.Sx GENERAL OPTIONS .
.It Fl N
Используйте альтернативный образ ядра
Смотреть
.Sx GENERAL OPTIONS .
.It Fl j Ar jail
Запустить внутри jail.
Смотреть
.Sx GENERAL OPTIONS .
.El
.It Xo
.Bk -words
.Nm
.Fl B
.Op Fl z
.Op Fl I Ar interface
.Op Fl j Ar jail
.Ek
.Xc
Показывать статистику о
.Xr bpf 4
одноранговых узлах.
Это включает в себя такую информацию, как
сколько пакетов было сопоставлено, отброшено и получено
устройством bpf, а также информация о текущих размерах буфера
и состояниях устройства.
.Pp

.Xr bpf 4
флаги, отображаемые при
.Nm
вызывается с помощью
.Fl B
параметр представляет собой базовые параметры узла bpf.
Каждый флаг является
представлен в виде одной строчной буквы.
Соответствие между буквами и флажками в порядке их появления выглядит следующим образом:
.Bl -column ".Li i"
.It Li p Ta Set if listening promiscuously
.It Li i Ta Dv BIOCIMMEDIATE No has been set on the device
.It Li f Ta Dv BIOCGHDRCMPLT No status: source link addresses are being
заполняется автоматически
.It Li s Ta Dv BIOCGSEESENT No status: see packets originating locally and
удаленно подключен к интерфейсу.
.It Li a Ta Packet reception generates a signal
.It Li l Ta Dv BIOCLOCK No status: descriptor has been locked
.El
.Pp
Для получения дополнительной информации об этих флагах, пожалуйста, обратитесь к
.Xr bpf 4 .
.Bl -tag -width indent
.It Fl z
Сбросьте статистические счетчики после их отображения.
.It Fl j Ar jail
Запустить внутри jail.
Смотреть
.Sx GENERAL OPTIONS .
.El
.It Xo
.Bk -words
.Nm
.Fl r
.Op Fl 46AnW
.Op Fl F Ar fibnum
.Op Fl f Ar address_family
.Op Fl M Ar core
.Op Fl N Ar system
.Op Fl j Ar jail
.Ek
.Xc
Отображение содержимого таблиц маршрутизации.
.Pp
Когда
.Nm
вызывается с помощью параметра таблица маршрутизации
.Fl r ,
в нем перечислены доступные маршруты и их статус.
Каждый маршрут состоит из узла назначения или сети и шлюза, который используется
для пересылки пакетов.
Поле "Флаги" отображает набор сведений о маршруте, сохраненных
в виде двоичных вариантов выбора.
Более подробно отдельные флаги обсуждаются в разделе
.Xr route 8
и
.Xr route 4
страницы руководства.
Соответствие между буквами и флагами таково:
.Bl -column ".Li W" ".Dv RTF_WASCLONED"
.It Li 1 Ta Dv RTF_PROTO1 Ta "Специальный флаг маршрутизации протокола #1"
.It Li 2 Ta Dv RTF_PROTO2 Ta "Специальный флаг маршрутизации протокола #2"
.It Li 3 Ta Dv RTF_PROTO3 Ta "Специальный флаг маршрутизации протокола #3"
.It Li B Ta Dv RTF_BLACKHOLE Ta "Просто отказаться от pkts (во время обновления)"
.It Li b Ta Dv RTF_BROADCAST Ta "Маршрут представляет собой широковещательный адрес"
.It Li D Ta Dv RTF_DYNAMIC Ta "Создаётся динамически (путем перенаправления)"
.It Li G Ta Dv RTF_GATEWAY Ta "Пункт назначения требует передачи через посредника"
.It Li H Ta Dv RTF_HOST Ta "Вход в узел (в противном случае - net)"
.It Li L Ta Dv RTF_LLINFO Ta "Действующий протокол для перевода адресов"
.It Li M Ta Dv RTF_MODIFIED Ta "Динамически модифицированный (путем перенаправления)"
.It Li R Ta Dv RTF_REJECT Ta "Хост или сеть недоступны"
.It Li S Ta Dv RTF_STATIC Ta "Добавлено вручную"
.It Li U Ta Dv RTF_UP Ta "Маршрут, который можно использовать"
.It Li X Ta Dv RTF_XRESOLVE Ta "Внешний daemon переводит прото в адрес ссылки"
.El
.Pp
Прямые маршруты создаются для каждого интерфейса,
подключенного к локальному хосту;
в поле шлюза для таких записей отображается адрес исходящего интерфейса.
Поле refcnt выдает следующее
текущее количество активных пользователей маршрута.
Протоколы, ориентированные на подключение,
бычно сохраняют один маршрут в течение всего времени действия соединения,
в то время как протоколы без установления соединения 
получают маршрут при отправке в тот же пункт назначения.
В поле use указывается количество пакетов,
отправленных по этому маршруту.
Запись интерфейса указывает сетевой интерфейс, используемый для маршрута.
.Bl -tag -width indent
.It Fl 4
Показывать только IPv4.
Смотреть
.Sx GENERAL OPTIONS .
.It Fl 6
Показывать только IPv6.
Смотреть
.Sx GENERAL OPTIONS .
.It Fl n
Не преобразуйте числовые адреса и номера портов в имена.
Смотреть
.Sx GENERAL OPTIONS .
.It Fl W
Укажите MTU пути для каждого маршрута и выведите названия интерфейсов с
увеличенным размером поля.
.It Fl F
Отобразить таблицу маршрутизации с номером
.Ar fibnum .
Если указанный
.Ar fibnum
будет -1 или
.Fl F
если этот параметр не указан,
отображается таблица маршрутизации по умолчанию.
.It Fl f
Отобразить таблицу маршрутизации для конкретного
.Ar address_family .
.It Fl M
Используйте альтернативное ядро
Смотреть
.Sx GENERAL OPTIONS .
.It Fl N
Используйте альтернативный образ ядра
Смотреть
.Sx GENERAL OPTIONS .
.It Fl j Ar jail
Запустить внутри jail.
Смотреть
.Sx GENERAL OPTIONS .
.El
.It Xo
.Bk -words
.Nm
.Fl rs
.Op Fl s
.Op Fl M Ar core
.Op Fl N Ar system
.Op Fl j Ar jail
.Ek
.Xc
Отображение статистики маршрутизации.
.Bl -tag -width indent
.It Fl s
Или
.Fl s
повторяется, счетчики с нулевым значением отключаются.
.It Fl M
Используйте альтернативное ядро
Смотреть
.Sx GENERAL OPTIONS .
.It Fl N
Используйте альтернативный образ ядра
Смотреть
.Sx GENERAL OPTIONS .
.It Fl j Ar jail
Запустить внутри jail.
Смотреть
.Sx GENERAL OPTIONS .
.El
.It Xo
.Bk -words
.Nm
.Fl g
.Op Fl 46W
.Op Fl f Ar address_family
.Op Fl M Ar core
.Op Fl N Ar system
.Op Fl j Ar jail
.Ek
.Xc
Отображать содержимое таблиц виртуального интерфейса
многоадресной рассылки и кэшей многоадресной пересылки.
Записи в этих таблицах будут отображаться только тогда, когда
ядро активно пересылает сеансы многоадресной рассылки.
Эта опция применима только к
.Cm inet
и
.Cm inet6
семейства адрессов.
.Bl -tag -width indent
.It Fl 4
Показывать только IPv4
Смотреть
.Sx GENERAL OPTIONS .
.It Fl 6
Показывать только IPv6
Смотреть
.Sx GENERAL OPTIONS .
.It Fl W
Избегайте усечения адресов, даже если это приводит к переполнению некоторых полей.
.It Fl f Ar protocol_family
Фильтровать по
.Ar protocol_family .
Смотреть
.Sx GENERAL OPTIONS .
.It Fl M
Используйте альтернативное ядро
Смотреть
.Sx GENERAL OPTIONS .
.It Fl N
Используйте альтернативный образ ядра
Смотреть
.Sx GENERAL OPTIONS .
.It Fl j Ar jail
Запустить внутри jail.
Смотреть
.Sx GENERAL OPTIONS .
.El
.It Xo
.Bk -words
.Nm
.Fl gs
.Op Fl 46s
.Op Fl f Ar address_family
.Op Fl M Ar core
.Op Fl N Ar system
.Op Fl j Ar jail
.Ek
.Xc
Отображение статистики многоадресной маршрутизации.
.Bl -tag -width indent
.It Fl 4
Показывать только IPv4
Смотреть
.Sx GENERAL OPTIONS .
.It Fl 6
Показывать только IPv6
Смотреть
.Sx GENERAL OPTIONS .
.It Fl s
Или
.Fl s
повторяется, счетчики с нулевым значением отключаются.
.It Fl f Ar protocol_family
Фильтровать по
.Ar protocol_family .
Смотреть
.Sx GENERAL OPTIONS .
.It Fl M
Используйте альтернативное ядро
Смотреть
.Sx GENERAL OPTIONS .
.It Fl N
Используйте альтернативный образ ядра
Смотреть
.Sx GENERAL OPTIONS .
.It Fl j Ar jail
Запустить внутри jail.
Смотреть
.Sx GENERAL OPTIONS .
.El
.It Xo
.Bk -words
.Nm
.Fl Q
.Op Fl j Ar jail
.Ek
.Xc
Показать
.Xr netisr 9
ститистику.
В поле флаги отображаются доступные обработчики ISR:
.Bl -column ".Li W" ".Dv NETISR_SNP_FLAGS_DRAINEDCPU"
.It Li C Ta Dv NETISR_SNP_FLAGS_M2CPUID Ta "Able to map mbuf to cpu id"
.It Li D Ta Dv NETISR_SNP_FLAGS_DRAINEDCPU  Ta "Has queue drain handler"
.It Li F Ta Dv NETISR_SNP_FLAGS_M2FLOW Ta "Able to map mbuf to flow id"
.It Fl j Ar jail
Запустить внутри jail.
Смотреть
.Sx GENERAL OPTIONS .
.El
.El
.Ss GENERAL OPTIONS
Некоторые варианты имеют общее значение:
.Bl -tag -width flag
.It Fl 4
Это сокращение от
.Fl f
.Ar inet
.Pq Show only IPv4
.It Fl 6
Это сокращение от
.Fl f
.Ar inet6
.Pq Show only IPv6
.It Fl f Ar address_family , Fl p Ar protocol
Ограничить отображение только теми записями
указанного
.Ar address_family
или одного-единственного
.Ar protocol .
Распознаются следующие семейства адресов и протоколы:
.Pp
.Bl -tag -width ".Cm netgraph , ng Pq Dv AF_NETGRAPH" -compact
.It Em Family
.Em Protocols
.It Cm inet Pq Dv AF_INET
.Cm divert , icmp , igmp , ip , ipsec , pim, sctp , tcp , udp
.It Cm inet6 Pq Dv AF_INET6
.Cm icmp6 , ip6 , ipsec6 , rip6 , sctp , tcp , udp
.It Cm pfkey Pq Dv PF_KEY
.Cm pfkey
.It Cm netgraph , ng Pq Dv AF_NETGRAPH
.Cm ctrl , data
.It Cm unix Pq Dv AF_UNIX
.It Cm link Pq Dv AF_LINK
.El
.Pp
Программа будет жаловаться, если
.Ar protocol
является неизвестным или для него не существует статистической процедуры.
.It Fl M
Извлеките значения, связанные со списком имен, из указанного ядра
вместо значений по умолчанию
.Pa /dev/kmem .
.It Fl N
Извлеките список имен из указанной системы вместо используемого по умолчанию
образа ядра, с которого система загрузилась.
.It Fl n
Отображать сетевые адреса и порты в виде цифр.
Обычно
.Nm
пытается определить адреса и порты
и отобразить их в символическом виде.
.It Fl W
Расширьте выходные данные; расширьте поля адресов и т.д., чтобы избежать усечения.
Нечисловые значения, такие как доменные имена, все еще могут быть усечены; используйте
.Fl n
выберите вариант, если это необходимо, чтобы избежать двусмысленности.
.It Fl j Ar jail
Выполните действия внутри
.Ar jail .
Это позволяет получить доступ к состоянию сети, даже если
.Cm netstat
двоичный файл недоступен в
.Ar jail .
.El
.Sh ПРИМЕРЫ
Отображение информации о трафике пакетов (пакеты, байты, ошибки, отбрасывания пакетов и т.д.) для
интерфейса re0 обновляется каждые 2 секунды и завершается через 5 выходов:
.Bd -literal -offset indent
$ netstat -w 2 -q 5 -I re0
.Ed
.Pp
Показывать статистику для ICMP на любом интерфейсе:
.Bd -literal -offset indent
$ netstat -s -p icmp
.Ed
.Pp
Показывать таблицы маршрутизации:
.Bd -literal -offset indent
$ netstat -r
.Ed
.Pp
То же, что и выше, но без преобразования числовых адресов и номеров портов в
имена:
.Bd -literal -offset indent
$ netstat -rn
.Ed
.Sh СОТРЕТЬ ТАКЖЕ
.Xr fstat 1 ,
.Xr nfsstat 1 ,
.Xr procstat 1 ,
.Xr ps 1 ,
.Xr sockstat 1 ,
.Xr libxo 3 ,
.Xr xo_parse_args 3 ,
.Xr bpf 4 ,
.Xr inet 4 ,
.Xr route 4 ,
.Xr unix 4 ,
.Xr hosts 5 ,
.Xr networks 5 ,
.Xr protocols 5 ,
.Xr services 5 ,
.Xr iostat 8 ,
.Xr route 8 ,
.Xr vmstat 8 ,
.Xr mbuf 9
.Sh ИСТОРИЯ

.Nm
команда появилась в
.Bx 4.2 .
.Pp
Поддержка IPv6 была добавлена проектом WIDE/KAME.
.Sh ПРОБЛЕМЫ
Понятие ошибок определено нечетко.
