.\" Авторское право (c) 2018 Edward Tomasz Napierala <trasz@FreeBSD.org>
.\"
.\" Распространение и использование в исходном коде и двоичном формате, с
.\" изменениями или без них, разрешено при соблюдении следующих условий:
.\" 1. При повторном распространении исходного кода должны сохраняться вышеуказанное
.\"    уведомление об авторских правах, этот список условий и следующий отказ от ответственности.
.\" 2. При повторном распространении в двоичной форме должны воспроизводиться вышеуказанное
.\"    уведомление об авторских правах, этот список условий и следующий отказ от ответственности в
.\"    документации и/или других материалах, прилагаемых к дистрибутиву.
.\"
.\" ДАННОЕ ПРОГРАММНОЕ ОБЕСПЕЧЕНИЕ ПРЕДОСТАВЛЯЕТСЯ АВТОРОМ "КАК ЕСТЬ", И
.\" МЫ НЕ ДАЕМ НИКАКИХ ЯВНЫХ ИЛИ ПОДРАЗУМЕВАЕМЫХ ГАРАНТИЙ, ВКЛЮЧАЯ
.\" ПОДРАЗУМЕВАЕМЫЕ ГАРАНТИИ ТОВАРНОЙ ПРИГОДНОСТИ И ПРИГОДНОСТИ ДЛЯ ОПРЕДЕЛЕННОЙ ЦЕЛИ И Т.П.
.\" АВТОР НИ В КОЕМ СЛУЧАЕ НЕ НЕСЕТ ОТВЕТСТВЕННОСТИ
.\" ЗА ЛЮБОЙ ПРЯМОЙ, КОСВЕННЫЙ, СЛУЧАЙНЫЙ, ОСОБЫЙ, ПОКАЗАТЕЛЬНЫЙ ИЛИ ЛОГИЧЕСКИ ВЫТЕКАЮЩИЙ
.\" УЩЕРБ (ВКЛЮЧАЯ: ПРИОБРЕТЕНИЕ ЗАМЕНЯЮЩИХ ТОВАРОВ ИЛИ УСЛУГ; ПОТЕРЮ ВОЗМОЖНОСТИ ИСПОЛЬЗОВАНИЯ,
.\" ДАННЫХ ИЛИ ПРИБЫЛИ; ПЕРЕБОИ В РАБОТЕ)
.\" НЕЗАВИСИМО ОТ ПРИЧИН И ПО ЛЮБОЙ ТЕОРИИ ОТВЕТСТВЕННОСТИ, БУДЬ ТО В КОНТРАКТЕ,
.\" ИЛИ ПРАВОНАРУШЕНИЕ (ВКЛЮЧАЯ ХАЛАТНОСТЬ ИЛИ ИНОЕ ПРАВОНАРУШЕНИЕ ИНЫМ ОБРАЗОМ),
.\" ВОЗНИКАЮЩЕЕ КАКИМ-ЛИБО ОБРАЗОМ В РЕЗУЛЬТАТЕ ИСПОЛЬЗОВАНИЯ ДАННОГО ПРОГРАММНОГО ОБЕСПЕЧЕНИЯ,
.\" ДАЖЕ ЕСЛИ ВЫ БЫЛИ ПРЕДУПРЕЖДЕНЫ О ВОЗМОЖНОСТИ ТАКОГО УЩЕРБА.
.\"
.Dd Ноябрь 1, 2022
.Dt DEVELOPMENT 7
.Os
.Sh НАИМЕНОВАНИЕ
.Nm development
.Nd введение в процесс разработки
.Fx
.Sh ОПИСАНИЕ
.Fx
разработка разделена на три основных подпроекта: doc, ports, and src.
Doc это документация, такая как руководство по
.Fx .
Чтобы узнать больше, смотрите:
.Pp
.Lk https://docs.FreeBSD.org/en/books/fdp-primer/
.Pp
Порты, описанные далее в разделе
.Xr ports 7 ,
представляют собой способ сборки, упаковки,
и установики программного обеспечения сторонних производителей.
Чтобы узнать больше, смотрите:
.Pp
.Lk https://docs.FreeBSD.org/en/books/porters-handbook/
.Pp
Последний же, src, снован на исходном коде базовой системы,
состоящем из ядра, а также библиотек и утилит, которые обычно
называются "мир"
.Pp
Руководство Пользователя, описывающее темы, актуальные для всех пользователей,
можно найти по адресу:
.Pp
.Lk https://docs.freebsd.org/en/articles/committers-guide/
.Pp
.Fx
src разработка осуществляется в размещенном в проекте репозитории Git,
расположенном по адресу:
.Pp
.Lk https://git.FreeBSD.org/src.git
.Pp
Активная URL ссылка ниже:
.Pp
.Lk ssh://git@gitrepo.FreeBSD.org/src.git
.Pp
Также есть список общедоступных зеркал Git, доступных только для чтения, по адресу:
.Pp
.Lk https://docs.FreeBSD.org/en/books/handbook/mirrors/#external-mirrors
.Pp
Основная
.Ql main
ветка Git соответствует ТЕКУЩЕЙ;
все изменения сначала вносятся в
ТЕКУЩУЮ, а затем, как правило, возвращаются в СТАБИЛЬНУЮ,
которая относится к веткам Git, таким как
.Ql stable/13 .
Каждые несколько лет новая СТАБИЛЬНАЯ версия отделяется от ТЕКУЩЕЙ,
с увеличением номера основной версии.
Затем релизы отделяются от СТАБИЛЬНОЙ и нумеруются последовательными минимальными
номерами.
.Pp
Структура дерева исходных текстов описана в его файле
.Pa README.md .
Инструкции по сборке можно найти в разделах
.Xr build 7
и
.Xr release 7 .
Программные интерфейсы ядра (KPIs) описаны на страницах руководства в разделе 9;
используйте
.Ql "apropos -s 9 ."
для получения списка.
Набор регрессионных тестов описан в разделе
.Xr tests 7 .
Правила кодирования приведены в разделе
.Xr style 9 .
.Pp
Чтобы задать вопросы, касающиеся разработки, используйте списки рассылок,
такие как freebsd-arch@ and freebsd-hackers@:
.Pp
.Lk https://lists.FreeBSD.org
.Pp
Чтобы интегрировать ваши исправления в основной репозиторий
.Fx ,
используйте Phabricator;
это инструмент проверки кода, который позволяет другим разработчикам
просматривать изменения, предлагать улучшения и, в конечном счете, позволяет им
подхватить изменения и зафиксировать их:
.Pp
.Lk https://reviews.FreeBSD.org
.Pp
Для проверки последней сборки
.Fx
и тестирования статуса ТЕКУЩЕЙ и СТАБИЛЬНОЙ версий
система непрерывной интеграции находится на:
.Pp
.Lk https://ci.FreeBSD.org
.Pp
.Sh ПРИМЕРЫ
Найдите ТЕКУЩУЮ ветку, соберите ее и установите, перезаписав
текущую систему:
.Bd -literal -offset indent
git clone https://git.FreeBSD.org/src.git src
cd src
make -sj8 buildworld buildkernel installkernel
shutdown -r now
.Ed
.Pp
После перезагрузки:
.Bd -literal -offset indent
cd src
make -j8 installworld
reboot
.Ed
.Pp
Перестроить и переустановить отдельный фрагмент пользовательского пространства,
в данном случае используйте
.Xr ls 1 :
.Bd -literal -offset indent
cd src/bin/ls
make clean all install
.Ed
.Pp
Быстро перестройте и переустановите ядро, только перекомпилировав файлы
измененные с момента последней сборки; обратите внимание,
что это сработает только в том случае,
если полная сборка ядра была завершена в прошлом,
а не в новом дереве исходных текстов:
.Bd -literal -offset indent
cd src
make -sj8 kernel KERNFAST=1
.Ed
.Pp
Чтобы перестроить части
.Fx
для другой архитектуры процессора, сначала подготовьте
свое дерево исходных текстов, создав перекрестную цепочку инструментов:
.Bd -literal -offset indent
cd src
make -sj8 toolchain TARGET_ARCH=aarch64
.Ed
.Pp
После этого, чтобы создать и установить единую часть пользовательского
пространства, используйте:
.Bd -literal -offset indent
cd src/bin/ls
make buildenv TARGET_ARCH=aarch64
make clean all install DESTDIR=/clients/arm
.Ed
.Pp
Аналогично, чтобы быстро перестроить и переустановить ядро, используйте:
.Bd -literal -offset indent
cd src
make buildenv TARGET_ARCH=aarch64
make -sj8 kernel KERNFAST=1 DESTDIR=/clients/arm
.Ed
.Sh СМОТРИТЕ ТАКЖЕ
.Xr git 1 ,
.Xr witness 4 ,
.Xr build 7 ,
.Xr hier 7 ,
.Xr ports 7 ,
.Xr release 7 ,
.Xr tests 7 ,
.Xr locking 9 ,
.Xr style 9
.Sh ИСТОРИЯ
Первоначально страница
.Nm
руководства по разработке была написана
.An Matthew Dillon Aq Mt dillon@FreeBSD.org
и впервые появилась во
.Fx 5.0 ,
Декабрь 2002.
С тех пор оно был значительно изменено 
.An Eitan Adler Aq Mt eadler@FreeBSD.org
чтобы отразить преобразование репозитория из
.Lk https://www.nongnu.org/cvs/ CVS
в
.Lk https://subversion.apache.org/ Subversion .
Оно была переписана с нуля
.An Edward Tomasz Napierala Aq Mt trasz@FreeBSD.org
для
.Fx 12.0 .
