.TH "local-unbound-checkconf" "8" "Feb 10, 2022" "NLnet Labs" "local-unbound 1.15.0"
.\"
.\" local-unbound-checkconf.8 -- local-unbound configuration checker manual
.\"
.\" Copyright (c) 2007, NLnet Labs. All rights reserved.
.\"
.\" See LICENSE for the license.
.\"
.\"
.SH "NAME"
local-unbound\-checkconf
\- Check Local-unbound configuration file for errors.
.SH "SYNOPSIS"
.B local-unbound\-checkconf
.RB [ \-h ]
.RB [ \-f ]
.RB [ \-o
.IR option ]
.RI [ cfgfile ]
.SH "DESCRIPTION"
.B Local-unbound\-checkconf
checks the configuration file for the
\fIlocal-unbound\fR(8)
DNS resolver for syntax and other errors.
The config file syntax is described in
\fIunbound.conf\fR(5).
.P
The available options are:
.TP
.B \-h
Show the version and commandline option help.
.TP
.B \-f
Print full pathname, with chroot applied to it.  Use with the \-o option.
.TP
.B \-o\fI option
If given, after checking the config file the value of this option is
printed to stdout.  For "" (disabled) options an empty line is printed.
.TP
.I cfgfile
The config file to read with settings for Unbound. It is checked.
If omitted, the config file at the default location is checked.
.SH "EXIT CODE"
The local-unbound\-checkconf program exits with status code 1 on error,
0 for a correct config file.
.SH "FILES"
.TP
.I @ub_conf_file@
Local-unbound configuration file.
.SH "SEE ALSO"
\fIunbound.conf\fR(5),
\fIlocal-unbound\fR(8).
